if --savedir is present, use it as final gameDir
MinicraftPlus/minicraft-plus-revived pull request #405
Opened 2022-10-07 09:37 UTC by KalmeMarq

Right now, when the --savedir is specified the game appends "/.playminicraft/mods/Minicraft Plus" to it. However, this should not be the case. If the user gives a path to use as the save dir then that should be the final path to use.

2022-10-08 09:27 UTC, Makkkkus requested changes
Add it to the changelog

2022-10-08 20:41 UTC, Makkkkus submitted a review, later dismissed

2022-11-05 19:37 UTC, Makkkkus requested changes
Some small changes

2022-11-05 19:37 UTC, Makkkkus commented on ChangeLog.txt
> +* Changed how the game uses the --savedir command line argument. Now, when specified, the game will use it as the final game directory path instead of adding an extra '.playminicraft/mods/Minicraft_P
You should probably rewrite this to make it shorter and simpler like the entries above it.

2022-11-05 19:37 UTC, Makkkkus commented on src/main/java/minicraft/core/io/FileHandler.java
> +	public static void determineGameDir(@Nullable String saveDir) {
Perhaps add some javadoc for this function.

2022-11-06 01:50 UTC, KalmeMarq commented
I don't know if the grammar is the best.

2022-11-06 10:54 UTC, Makkkkus approved these changes
All my problems are addressed. Good job!

2022-11-06 12:12 UTC, ChristofferHolmesland approved these changes
Looks good. Commit messages could be more clear.

2022-11-06 12:12 UTC, merged