Storyline lore
MinicraftPlus/minicraft-plus-revived pull request #476
Opened 2023-05-15 23:46 UTC by Litorom

Adds lore books to be found in chests
Follows the original theme alone and Obsidian Knight hold on further growth.

Closes #304

2023-06-20 15:34 UTC, Makkkkus requested changes
Please avoid grammatical mistakes. Perhaps attempt to to a website that can improve your writing? For example: "Knight" should only be written with a capital "K" in the start of sentences. In addition, "..." is acceptable", but in those cases I advise you to consistently follow the AP stylebook.

I also notice some weird choices when it comes to the words and sentences you create. "Throughout countless eons" and "Banished from their home to fend in another world", for example. "Once upon a time, in a space far far away", makes no sense at all. What is a space? It is incredibly ambigous. Also, Star Wars?

I also see some mixing of British and American English (GB: "learnt", US: "armor"). Try using one consistently instead of mixing the two. Ideally you would use British English, but that is personal taste.

In difference to form, the actual contents are pretty good. Just fix up these minor issues and you'll be set.

2023-06-20 20:03 UTC, Litorom commented
> Please avoid grammatical mistakes. Perhaps attempt to to a website that can improve your writing? For example: "Knight" should only be written with a capital "K" in the start of sentences. In addition, "..." is acceptable", but in those cases I advise you to consistently follow the AP stylebook.
> 
> I also notice some weird choices when it comes to the words and sentences you create. "Throughout countless eons" and "Banished from their home to fend in another world", for example. "Once upon a time, in a space far far away", makes no sense at all. What is a space? It is incredibly ambigous. Also, Star Wars?
> 
> I also see some mixing of British and American English (GB: "learnt", US: "armor"). Try using one consistently instead of mixing the two. Ideally you would use British English, but that is personal taste.
> 
> In difference to form, the actual contents are pretty good. Just fix up these minor issues and you'll be set.

I see, I understand that my writing is wonky at times. As for “Obsidian Knight” is a person (entity), I feel should be capitalized. As for British vs American English, “learnt” i didn’t know was a British term.

2023-06-20 20:04 UTC, Makkkkus commented
The Obsidian Knight and Knight are two completely different things.

2023-06-20 20:06 UTC, Litorom commented
> The "Obsidian Knight" and a "Knight" are two completely different things.

Yes, I realized that one capitalized “Knight” now. I’ll fix that grammar.

2023-07-19 20:43 UTC, Makkkkus commented
Closing because of lacking activity.

2023-08-22 12:50 UTC, BenCheung0422 commented
There could be some types of lore books:
- pages - a complete page of the storyline describing the story.
- pieces of papers - a part of a page, may be including placeholders like `[Lost content]` or `[Unclear content]`, "*The text written left is blur and unclear*".
- book series - a complete part of a set of book series, may be story books.

Then, we could have different types of contents in the books:
- diaries - texts left or daily living/adventure experiences written by forerunners or some mobs included in the historical storyline.
- god's text - messages by the story narrator.
- stories - some stories written by somethings or describing the storyline.

2023-08-22 13:48 UTC, BenCheung0422 commented
As Eye mentioned that the game without a fixed story might be more attractive to people, I would like to suggest that we should keep this storyline lore be small and concise, without overinterpreting the storyline. Also, the lore should be kept as the background of the game, so it is the story of the game. By the way, there has already been "Antidious" in the game, which is written in 2012 as a short story, so we should also include this story in the game. The book is dropped by skeleton with a small chance.

2024-01-31 21:02 UTC, closed without merging

2024-02-01 09:39 UTC, BenCheung0422 commented
Actually I think of a way to implement lore book generation better with help of the world generation tweaks.

2024-02-01 13:16 UTC, Litorom commented
That doesn’t change the issue with old worlds. We don’t have pointers to old structures like abandoned villages to add or spawn a chest to.

2024-02-01 14:11 UTC, BenCheung0422 commented
Well, we can have a temporary item that can be crafted and used to generate the desired structures. This item can be disused and made as souvenir when infinity generation is done.

2024-02-01 14:24 UTC, Litorom commented
Tbh what’s not a bad idea however, it could theoretically be exploited and overpowered. To a certain degree we could prevent this but idk.