Move torch variations into tile data
MinicraftPlus/minicraft-plus-revived pull request #555
Opened 2023-08-09 15:18 UTC by BenCheung0422

Using duplications in the main method is not a great idea, so this changes torch tile variations into handling the tile data instead. When #437 is merged, `TileModel` can be used to merge `TorchItem` into a general `TileItem` instance.

2023-08-16 17:54 UTC, ChristofferHolmesland requested changes

2023-08-16 17:54 UTC, ChristofferHolmesland commented on src/client/java/minicraft/level/Level.java
> +		return (tile = Tiles.get(id)) == TorchTile.DELEGATE ? TorchTile.getTorchTile(Tiles.get((short) getData(x, y))) : tile;
This should be changed to something that is more readable. Suggestion:
```
Tile tile = Tiles.get(id);

if (tile == TorchTile.DELEGATE) {
  return TorchTile.getTorchTile(Tiles.get((short)) getData(x, y)));
}

return tile;
```

2023-11-10 11:11 UTC, ChristofferHolmesland submitted a review, later dismissed

2023-11-10 23:55 UTC, Makkkkus approved these changes

2024-02-12 17:39 UTC, Litorom commented
Please fix conflicts.

2024-02-12 23:31 UTC, Makkkkus requested changes
Actually, when looking at this again, won't this break all saves that have torches?

2024-02-13 09:45 UTC, BenCheung0422 commented
The code to load torch is not removed, so it is not affected.

2024-02-13 10:22 UTC, BenCheung0422 commented
Conflicts resolved.

2024-02-13 14:50 UTC, Makkkkus commented
> The code to load torch is not removed, so it is not affected.

Yes, but then it tries to load the tourch with a the old name on new saves. That will cause an error.

2024-02-13 14:52 UTC, BenCheung0422 commented
I fixed that error in the latest commit recently.

2024-03-28 12:54 UTC, merged